### PR TITLE
chore(release): setup git user

### PR DESCRIPTION
**Pull request by yshrsmz**
related: #11 

setup git user to fix release error

### CODE REVIEW

**Review by kettanaito — APPROVED** [review]
Thank you for such a swift follow-up! You're the best.

**Comment by yshrsmz** [comment]
https://github.com/mswjs/http-middleware/runs/6717592247?check_suite_focus=true

It says 0.4.0 was already there.
Looks like it was released, but could not update GitHub due to the lack of git config 🤔

**Comment by kettanaito** [comment]
You're right. That's an interesting case. I think I should check for the Git config early in Release and fail fast. You cannot revert the published package, and commit happens after the package has been published. A good catch.

**Comment by kettanaito** [comment]
I've added this behavior [as an idea to improve Release](https://github.com/ossjs/release/discussions/29). I wrote this release library so I can fix this as well.

**Pull request merged**
